env:
    browser: true
    es2021: true
    node: true
    jest: true
extends:
    - eslint:recommended
    - plugin:vue/essential
    - plugin:@typescript-eslint/recommended
    - plugin:prettier/recommended
root: true
parser: 'vue-eslint-parser'
parserOptions:
    ecmaVersion: latest
    parser: '@typescript-eslint/parser'
    sourceType: module
plugins:
    - vue
    - '@typescript-eslint'
rules:
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
    'vue/multi-word-component-names': off
    'vue/no-v-for-template-key': off
ignorePatterns:
    - '.eslintrc.js'
    - 'changelog.config.js'
    - 'commitlint.config.js'
