version: "3"
services:
    client:
        container_name: x-forward-client
        image: x-forward-client:latest
        restart: always
        env_file:
            - .env
        ports:
            - "5000:5000"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
    db:
        container_name: x-forward-db
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: logs
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
    server:
        container_name: x-forward-server
        image: x-forward-server:latest
        restart: always
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - "3000:3000"
            - "3001:3001"
            - "1234:1234"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "10"
