# nginx + node + pm2

FROM nginx

# Create app directory
WORKDIR /usr/src/app

# change apt source
RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# install node
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get -y update

RUN apt-get install -y wget gpg
RUN apt-get install -y nodejs
RUN apt-get install -y goaccess

# manage nginx logs with goaccess
RUN wget -O - https://deb.goaccess.io/gnugpg.key | gpg --dearmor \
    | tee /usr/share/keyrings/goaccess.gpg >/dev/null
RUN echo "deb [signed-by=/usr/share/keyrings/goaccess.gpg] https://deb.goaccess.io/ $(lsb_release -cs) main" \
    | tee /etc/apt/sources.list.d/goaccess.list

# manage node project with pm2
RUN npm install pm2 -g

# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY packages/app/package*.json ./

# Install app dependencies
RUN npm install

# If you are building your code for production
# RUN npm ci --only=production
# Bundle app source
COPY packages/app/index.js .

EXPOSE 9000

CMD service nginx start && pm2-runtime index.js