# nginx + node + pm2
FROM nginx

ARG SHARED_VERSION=0.0.3

# Create app directory
WORKDIR /usr/x-forward

# change apt source
RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

# install node
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs python3 make build-essential

# Bundle APP files
# When using COPY with more than one source file, the destination must be a directory and end with a /
COPY packages/app/dist/apps/x-forward-client/* ./
COPY packages/app/protos ./protos
COPY packages/app/package.json .
RUN sed -i "s/workspace:\*/^${SHARED_VERSION}/g" package.json
COPY packages/app/apps/x-forward-server/ecosystem.config.js .

# manage node project with pm2
RUN npm install pm2 -g --registry=https://registry.npmmirror.com

# Install app dependencies
RUN npm i --production --registry=https://registry.npmmirror.com

EXPOSE 5000

CMD service nginx start && pm2-runtime start ecosystem.config.js
